version: '3.1'
services:
  mongo:
    container_name: mongodb-${PROJECT_NAME}
    image: mongo:latest
    restart: always
    ports:
      - ${DB_MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./data/mongodb:/data/db

  postgres:
    container_name: postgres-${PROJECT_NAME}
    image: postgres:latest
    restart: always
    ports:
      - ${DB_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/postgres:/var/lib/postgresql/data
      - ./script.sh:/docker-entrypoint-initdb.d/script.sh
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  api:
    container_name: api-${PROJECT_NAME}
    image: node:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
